# =============================================================================
# WamTrainingDisable.config.psd1 -- Shipped default configuration
# =============================================================================
#
# This file is the LOWEST precedence layer in the configuration stack.
# Resolve-WamConfiguration walks the layers in this order, with later
# entries overriding earlier ones:
#
#   1. Shipped defaults (this file)
#   2. -ConfigPath parameter (an explicit project file)
#   3. User config: $env:LOCALAPPDATA\WamTrainingDisable\config.psd1 on
#      Windows, or $HOME/.config/WamTrainingDisable/config.psd1 on Linux
#   4. Environment variables (WAM_SQL_CONNECTION, WAM_LOG_DIR, ...)
#   5. Cmdlet parameters (highest precedence)
#
# An override at level N replaces the value from level <N for the same key
# only; unspecified keys fall through to the lower layer. The merge is
# deep -- nested hashtables (like Logging.FileNameFormat) are merged
# key-by-key rather than wholesale-replaced.
#
# Why .psd1 and not .json or .yaml?
# ---------------------------------
# Per ADR 0007: .psd1 is data-only by spec (no Invoke-Expression risk on a
# tampered file), supports comments natively (so ops can leave a sticky
# note next to a connection string), is signable like any .ps1 file, and
# is what Test-ModuleManifest, Import-PowerShellDataFile, and the rest of
# the PowerShell ecosystem already speak. JSON loses comments; YAML adds
# a non-shipping module dependency.
#
# Editing this file
# -----------------
# Do NOT edit this file in production. It ships with the module and is
# overwritten on every module update. Override the keys you need in your
# own config file at one of the precedence levels above. The shipped
# defaults are the documented contract; everything else is your hook.
# =============================================================================

@{

    # -------------------------------------------------------------------------
    # Sql: the source-of-truth for "who is non-compliant."
    # -------------------------------------------------------------------------
    # The shipped ConnectionString is intentionally a placeholder. The prod
    # value lives in the maintainer's environment, NOT in this repo (the
    # repo is public and that hostname would be a leak). Override
    # ConnectionString in a level-3 user config or a level-4 env var.
    # -------------------------------------------------------------------------
    Sql = @{
        # Format: standard SQL Server ADO.NET connection string. The prod
        # value uses Integrated Security; if your environment uses SQL
        # auth, supply User ID and Password here -- but be aware that a
        # password in a .psd1 on disk is a credential leak unless the
        # file is ACL'd to the service account.
        ConnectionString = 'Server=SET_ME;Database=WebTraining;Integrated Security=True'

        # Stored procedure name. This is org-specific; the procedure
        # returns one row per non-compliant user with at minimum an
        # nt_username column.
        StoredProcedure = 'orc.get_Pers_Training_Disable_Accounts'

        # Column to read the username from. v1 hard-codes 'nt_username';
        # v2 makes it configurable in case the procedure schema ever
        # changes.
        UsernameColumn = 'nt_username'

        # Command timeout in seconds. The default ADO.NET command timeout
        # is 30 seconds; we lift it to 60 because the procedure is
        # expensive (it joins training records to roster snapshots) and
        # has been observed to take 35-40 seconds during peak times.
        CommandTimeoutSeconds = 60
    }

    # -------------------------------------------------------------------------
    # Policy: the exemption rules.
    # -------------------------------------------------------------------------
    Policy = @{
        # Number of days a newly-created account is exempt from disablement.
        # The clock starts at whenCreated. v1 uses 30; v2 keeps the same
        # default for drop-in compatibility.
        GracePeriodDays = 30

        # Names of OUs whose users are exempt. v1 had three booleans
        # ($VIP, $REL, $SCO); v2 collapses to a list because the booleans
        # were ergonomically awkward (every new exempt OU required a
        # script edit and a config edit). VIP is NOT in the default list
        # because v1's default was VIP=$false; users in OU=VIP are
        # actioned, but routed to the VIP log channel for the VIP
        # support team's awareness.
        ExemptOus = @(
            'REL'
            'SCO'
        )

        # Names of AD groups whose members are exempt. v1's $Exempt array
        # is preserved verbatim; the matcher is case-insensitive equality
        # in v2 (v1 used regex partial match via -match, which had
        # surprising behavior; see ADR -- to be filed in PR 4 -- about
        # the matcher unification).
        ExemptGroups = @(
            'VIP No Tng Req'
            'Temp No Tng Req'
        )

        # The wildcard pattern used to match an OU name against a user's
        # DistinguishedName. v1 used '*OU={0}*' inline (unwritten as a
        # convention); v2 hoists it as a config key so the matcher
        # behavior is testable and overridable.
        OuMatchPattern = '*OU={0}*'
    }

    # -------------------------------------------------------------------------
    # Logging: where the four output files go and how their lines are
    # formatted.
    # -------------------------------------------------------------------------
    Logging = @{
        # The base directory. The {0} is filled in with the run's date as a
        # yyyyMMdd string by Resolve-WamConfiguration. v1 hard-codes
        # 'C:\PS\Script_Output\WAM\<date>'; we keep the same path so the
        # drop-in shim writes to the location ops already expects.
        Directory = 'C:\PS\Script_Output\WAM\{0:yyyyMMdd}'

        # Log file encoding. v1 uses ASCII; we honor that for the main /
        # VIP / exempt logs because downstream consumers may parse the
        # files with tools that do not handle the UTF-8 BOM.
        Encoding = 'ascii'

        # Whether to write the LockoutList_<date>.txt file. v1 always writes
        # it (the file is the IPC handoff between the SQL stage and the
        # AD stage). v2 keeps writing it by default because at least one
        # downstream auditor reportedly grep's that file directly.
        WriteLockoutListFile = $true

        # Timestamp format string used by ConvertTo-WamLogLine. v2 default
        # is ISO 8601 (culture-invariant), which fixes a v1 bug where the
        # timestamp format depended on the runner's CurrentCulture. The
        # LegacyTimestamp opt-in (below) reverts to v1's culture-dependent
        # shape for downstream consumers that depend on it.
        TimestampFormat = 'yyyy-MM-dd HH:mm:ss'

        # Opt-in legacy timestamp shape. When $true, ConvertTo-WamLogLine
        # ignores TimestampFormat and reproduces v1's
        # "(get-date).ToShortDateString() + ' ' + (get-date).ToLongTimeString()"
        # output exactly. Use only if a downstream parser is known to
        # depend on the v1 shape. See open gap 0003.
        LegacyTimestamp = $false

        # File-name templates. The {0} is filled with the run's date as a
        # yyyyMMdd string. v1's filenames are pinned by ADR 0006 (the VIP
        # file is a downstream contract); v2 keeps them.
        FileNameFormat = @{
            Main = 'LockoutUsers_All_{0:yyyyMMdd}.log'
            Vip = 'LockoutUsers_VIP_{0:yyyyMMdd}.log'
            Exempt = 'LockoutUsers_EXEMPT_{0:yyyyMMdd}.log'
            Lockout = 'LockoutList_{0:yyyyMMdd}.txt'
        }

        # Channel routing rules.
        Channels = @{
            # The DN-pattern that triggers VIP channel emission. v1 had
            # a confusing inconsistency between '*VIP' (suffix) in
            # WAM-Disable and '*OU=VIP*' (substring) in WAM-ADSearch;
            # v2 settles on the substring form for both. The pattern is
            # exposed here so future contributors can see what the rule
            # actually is.
            VipDistinguishedNamePattern = '*OU=VIP*'
        }
    }
}
