# =============================================================================
# tests/Integration/DropInCompat.Tests.ps1 -- WAM Training Disable
# =============================================================================
#
# Purpose
# -------
# This is the safety net that protects v1's prod-deployed scheduled task
# from accidental breakage during the v2 modernization. Each subsequent
# PR (PR 3-7) introduces refactor surface; this test asserts that the
# OBSERVABLE behavior of running src/TrainingDisable.ps1 has not changed:
#
#   1. The same four output files appear at the same v1-shaped paths.
#   2. The lockout list contains the v1-expected set of usernames.
#   3. The main / VIP / exempt logs contain the v1-expected message lines
#      (with timestamps and hostnames stripped, since those vary per run).
#   4. With ReportOnly = $true the AD module is never written to.
#   5. With ReportOnly = $false the same set of users is the same set of
#      Disable-ADAccount targets, with the same description suffix on
#      Set-ADUser, that v1 would have produced.
#
# When PR 7 lands (the drop-in shim that delegates to the v2 module), this
# test is the contract that proves the rewrite did not break the prod
# scheduled task.
#
# Where the fixtures came from
# ----------------------------
# The expected/ files were generated by tests/fixtures/v1/_capture.ps1
# during PR 2 and reviewed before commit. To regenerate them after a
# fixture-input change:
#
#     pwsh -NoProfile -File tests/fixtures/v1/_capture.ps1
#
# The capture script and this test SHARE the harness (V1Sandbox.ps1) and
# the fixture inputs (the AdRecords / GroupRecords below). That sharing is
# deliberate: if the inputs in the two files drift apart, the fixtures
# match the capture but not the test, and CI fails loudly.
#
# What this test deliberately does NOT cover
# ------------------------------------------
# - v1's SQL stage. Replaced by a stub. The v1 SQL bug (Select-Object
#   -Index 0 truncates results) is locked separately by unit tests on
#   v2's Get-WamNonCompliantUser in PR 5.
#
# - v1's behavior on Get-ADUser identity-not-found. The "user vanishes
#   between SQL pull and AD lookup" path triggers a v1 bug where
#   $ADAccount carries over from the previous iteration; that is a
#   separate test in PR 4's exemption-matrix suite.
#
# - Encoding / line-ending exactness. We compare line-by-line as text,
#   normalizing CR/LF, because the prod Windows runtime and the Linux CI
#   runner produce slightly different byte sequences for the same logical
#   content.
# =============================================================================

#Requires -Version 5.1

Set-StrictMode -Version 3.0
$ErrorActionPreference = 'Stop'

BeforeDiscovery {
    # In Pester 5, BeforeDiscovery runs during the discovery phase and is
    # where we can compute paths used in the Describe/Context/It names.
    # We do not have any data-driven test names in this file, so this
    # block stays empty for now -- but Pester complains if BeforeAll
    # references $PSScriptRoot before the script has been discovered, so
    # we keep the block as a discoverable anchor.
}

BeforeAll {
    # Resolve repo paths from this script's location. Using $PSScriptRoot
    # is the Pester-recommended pattern; it works whether the test is
    # invoked from the repo root, from inside ./tests, or from a CI step
    # that uses an arbitrary working directory.
    $script:RepoRoot = (Resolve-Path -Path (Join-Path -Path $PSScriptRoot -ChildPath '../..')).Path
    $script:V1Path = Join-Path -Path $script:RepoRoot -ChildPath 'src/TrainingDisable.ps1'
    $script:FixtureDir = Join-Path -Path $script:RepoRoot -ChildPath 'tests/fixtures/v1'
    $script:ExpectedDir = Join-Path -Path $script:FixtureDir -ChildPath 'expected'

    # Dot-source the harness. It exposes Invoke-V1InSandbox and
    # ConvertTo-NormalizedV1LogLine. We dot-source rather than import-as-module
    # because the helper has no manifest and is a single-purpose internal
    # tool.
    . (Join-Path -Path $PSScriptRoot -ChildPath '_helpers/V1Sandbox.ps1')

    # -------------------------------------------------------------------------
    # Fixture inputs (kept in sync with tests/fixtures/v1/_capture.ps1).
    # -------------------------------------------------------------------------
    # If you add a user here, add them in the capture script too. The two
    # lists exist as separate copies on purpose: the capture script must
    # be runnable without invoking Pester (so the maintainer can regenerate
    # fixtures with raw pwsh in a constrained environment), and the test
    # must be runnable without invoking the capture script (so CI doesn't
    # need to write fixtures, only compare against them).
    #
    # The pinned $PinnedNow and the offsets used to compute whenCreated
    # MUST match the capture script. CI will catch a drift when the
    # snapshot comparison fails.
    # -------------------------------------------------------------------------
    $script:UsernameList = @(
        'alice.normal'
        'bob.disabled'
        'carol.grace'
        'dan.rel'
        'eve.sco'
        'frank.group'
    )

    $pinnedNow = [datetime]'2026-05-08T10:30:00'

    $script:AdRecords = @{
        'alice.normal' = @{
            Name = 'Alice Normal'
            Enabled = $true
            whenCreated = $pinnedNow.AddDays(-90)
            Department = 'Engineering'
            OfficePhone = '555-0001'
            Description = 'Software Engineer II'
            DistinguishedName = 'CN=alice.normal,OU=Users,DC=example,DC=com'
            MemberOf = @()
        }
        'bob.disabled' = @{
            Name = 'Bob Disabled'
            Enabled = $false
            whenCreated = $pinnedNow.AddDays(-90)
            Department = 'Engineering'
            OfficePhone = '555-0002'
            Description = 'Software Engineer II'
            DistinguishedName = 'CN=bob.disabled,OU=Users,DC=example,DC=com'
            MemberOf = @()
        }
        'carol.grace' = @{
            Name = 'Carol Grace'
            Enabled = $true
            whenCreated = $pinnedNow.AddDays(-10)
            Department = 'Engineering'
            OfficePhone = '555-0003'
            Description = 'Software Engineer I'
            DistinguishedName = 'CN=carol.grace,OU=Users,DC=example,DC=com'
            MemberOf = @()
        }
        'dan.rel' = @{
            Name = 'Dan REL'
            Enabled = $true
            whenCreated = $pinnedNow.AddDays(-90)
            Department = 'Engineering'
            OfficePhone = '555-0004'
            Description = 'Software Engineer II'
            DistinguishedName = 'CN=dan.rel,OU=REL,OU=Users,DC=example,DC=com'
            MemberOf = @()
        }
        'eve.sco' = @{
            Name = 'Eve SCO'
            Enabled = $true
            whenCreated = $pinnedNow.AddDays(-90)
            Department = 'Engineering'
            OfficePhone = '555-0005'
            Description = 'Software Engineer II'
            DistinguishedName = 'CN=eve.sco,OU=SCO,OU=Users,DC=example,DC=com'
            MemberOf = @()
        }
        'frank.group' = @{
            Name = 'Frank Group'
            Enabled = $true
            whenCreated = $pinnedNow.AddDays(-90)
            Department = 'Engineering'
            OfficePhone = '555-0006'
            Description = 'Software Engineer II'
            DistinguishedName = 'CN=frank.group,OU=Users,DC=example,DC=com'
            MemberOf = @('CN=VIP No Tng Req,OU=Groups,DC=example,DC=com')
        }
    }

    $script:GroupRecords = @{
        'CN=VIP No Tng Req,OU=Groups,DC=example,DC=com' = 'VIP No Tng Req'
    }

    # -------------------------------------------------------------------------
    # Helper: load an expected fixture file as an array of LF-normalized
    # lines, dropping a trailing empty line if present. PowerShell's
    # Set-Content emits a final newline on Windows that becomes one extra
    # empty array element when we re-read; we trim it so the comparison
    # is stable across the writer's choice.
    # -------------------------------------------------------------------------
    function script:Get-ExpectedLines {
        [CmdletBinding()]
        [OutputType([string[]])]
        param(
            [Parameter(Mandatory)]
            [string] $Path
        )
        $raw = Get-Content -Path $Path -Raw -Encoding utf8
        $lines = $raw -split "`r?`n"
        if ($lines.Length -gt 0 -and $lines[-1] -eq '') {
            $lines = $lines[0..($lines.Length - 2)]
        }
        return $lines
    }

    # -------------------------------------------------------------------------
    # Helper: read an actual log file produced by the harness, strip the
    # variable [<timestamp>] [<host>] prefix, and return the lines for
    # comparison.
    # -------------------------------------------------------------------------
    function script:Get-ActualNormalizedLines {
        [CmdletBinding()]
        [OutputType([string[]])]
        param(
            [Parameter(Mandatory)]
            [string] $Path
        )
        $raw = Get-Content -Path $Path -Raw -Encoding utf8
        $lines = $raw -split "`r?`n"
        if ($lines.Length -gt 0 -and $lines[-1] -eq '') {
            $lines = $lines[0..($lines.Length - 2)]
        }
        return @($lines | ConvertTo-NormalizedV1LogLine)
    }
}

Describe 'v1 drop-in compatibility (snapshot)' {

    Context 'with default config (ReportOnly = $true)' {

        BeforeAll {
            # Use $TestDrive so Pester cleans the sandbox up automatically
            # at the end of the Describe. The 'default' subdirectory keeps
            # the two contexts isolated from each other.
            $defaultWorkDir = Join-Path -Path $TestDrive -ChildPath 'default'

            $script:DefaultResult = Invoke-V1InSandbox `
                -V1ScriptPath $script:V1Path `
                -WorkingDirectory $defaultWorkDir `
                -UsernameList $script:UsernameList `
                -AdRecords $script:AdRecords `
                -GroupRecords $script:GroupRecords `
                -DateString '20260508' `
                -ComputerName 'TESTHOST'
        }

        It 'writes the lockout list to the v1-shaped path' {
            $script:DefaultResult.LockoutListFile | Should -Match 'LockoutList_20260508\.txt$'
            Test-Path -Path $script:DefaultResult.LockoutListFile | Should -BeTrue
        }

        It 'writes the lockout list with the expected usernames' {
            $expected = Get-ExpectedLines -Path (Join-Path $script:ExpectedDir 'lockout-list.txt')
            $actual = Get-ExpectedLines -Path $script:DefaultResult.LockoutListFile
            $actual | Should -Be $expected
        }

        It 'writes the main log to the v1-shaped path' {
            $script:DefaultResult.LogFileALL | Should -Match 'LockoutUsers_All_20260508\.log$'
            Test-Path -Path $script:DefaultResult.LogFileALL | Should -BeTrue
        }

        It 'writes the main log with the expected message lines' {
            $expected = Get-ExpectedLines -Path (Join-Path $script:ExpectedDir 'main.normalized.log')
            $actual = Get-ActualNormalizedLines -Path $script:DefaultResult.LogFileALL
            $actual | Should -Be $expected
        }

        It 'writes the VIP log to the v1-shaped path' {
            $script:DefaultResult.LogFileVIP | Should -Match 'LockoutUsers_VIP_20260508\.log$'
            Test-Path -Path $script:DefaultResult.LogFileVIP | Should -BeTrue
        }

        It 'writes the VIP log with the expected message lines (BEGIN/END only)' {
            $expected = Get-ExpectedLines -Path (Join-Path $script:ExpectedDir 'vip.normalized.log')
            $actual = Get-ActualNormalizedLines -Path $script:DefaultResult.LogFileVIP
            $actual | Should -Be $expected
        }

        It 'writes the exempt log to the v1-shaped path' {
            $script:DefaultResult.LogFileExempt | Should -Match 'LockoutUsers_EXEMPT_20260508\.log$'
            Test-Path -Path $script:DefaultResult.LogFileExempt | Should -BeTrue
        }

        It 'writes the exempt log with the expected message lines' {
            $expected = Get-ExpectedLines -Path (Join-Path $script:ExpectedDir 'exempt.normalized.log')
            $actual = Get-ActualNormalizedLines -Path $script:DefaultResult.LogFileExempt
            $actual | Should -Be $expected
        }

        It 'attempts no Disable-ADAccount calls (ReportOnly short-circuits)' {
            $script:DefaultResult.DisableCalls.Count | Should -Be 0
        }

        It 'attempts no Set-ADUser calls (ReportOnly short-circuits)' {
            $script:DefaultResult.SetUserCalls.Count | Should -Be 0
        }
    }

    Context 'with enforcement config (ReportOnly = $false)' {

        BeforeAll {
            $enforcementWorkDir = Join-Path -Path $TestDrive -ChildPath 'enforcement'

            $script:EnforcementResult = Invoke-V1InSandbox `
                -V1ScriptPath $script:V1Path `
                -WorkingDirectory $enforcementWorkDir `
                -UsernameList $script:UsernameList `
                -AdRecords $script:AdRecords `
                -GroupRecords $script:GroupRecords `
                -ConfigOverrides @{ ReportOnly = $false } `
                -DateString '20260508' `
                -ComputerName 'TESTHOST'

            # Load the pinned AD calls fixture once so each It block can
            # assert against it.
            $adCallsPath = Join-Path -Path $script:ExpectedDir -ChildPath 'ad-calls.enforcement.json'
            $script:ExpectedAdCalls = Get-Content -Path $adCallsPath -Raw -Encoding utf8 | ConvertFrom-Json
        }

        It 'attempts exactly one Disable-ADAccount call (alice.normal)' {
            $script:EnforcementResult.DisableCalls.Count | Should -Be 1
            $script:EnforcementResult.DisableCalls[0].Identity | Should -Be 'alice.normal'
        }

        It 'attempts exactly one Set-ADUser call (alice.normal)' {
            $script:EnforcementResult.SetUserCalls.Count | Should -Be 1
            $script:EnforcementResult.SetUserCalls[0].Identity | Should -Be 'alice.normal'
        }

        It 'sets the description to the v1-shaped suffix (with the v1 missing-paren typo preserved)' {
            # The fixture pins the EXACT description v1 would write to AD.
            # The pinned string includes a culture-dependent date and a
            # known v1 typo (an opening '(' with no matching close). Both
            # quirks must round-trip identically until v2 actively fixes
            # them in a later PR.
            $expected = $script:ExpectedAdCalls.SetUserCalls[0].Description
            $actual = $script:EnforcementResult.SetUserCalls[0].Description
            $actual | Should -Be $expected
        }

        It 'matches the pinned AD-calls JSON fixture verbatim' {
            $actualPayload = [pscustomobject] @{
                DisableCalls = $script:EnforcementResult.DisableCalls
                SetUserCalls = $script:EnforcementResult.SetUserCalls
            }
            $actualJson = $actualPayload | ConvertTo-Json -Depth 4

            # Re-serialize the expected payload through the same converter
            # so cosmetic differences (key ordering, indentation) do not
            # cause a false negative. The semantic comparison is the goal.
            $expectedPayload = [pscustomobject] @{
                DisableCalls = $script:ExpectedAdCalls.DisableCalls
                SetUserCalls = $script:ExpectedAdCalls.SetUserCalls
            }
            $expectedJson = $expectedPayload | ConvertTo-Json -Depth 4

            $actualJson | Should -Be $expectedJson
        }
    }
}
